# 1. This generates perfect Canonical Tags and Sitemap URLs
baseURL = "https://luckytaorem.github.io/blog/"


# 2. This tells Hugo to automatically generate a robots.txt file
enableRobotsTXT = true

# 3. Optional: Ensures your URLs are clean (no ugly .html at the end)
uglyURLs = false

title = "LT Developer"
locale = "en-us"

[module]
  [[module.imports]]
    path = "github.com/gethinode/hinode"

[params.main]
  endorse = false

[params.footer]
  copyright = "© 2026 LT Developer. All rights reserved."

[params.navigation]
  logo = "img/logo.png"


# --- TOP NAVIGATION MENU ---
[[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[menus.main]]
  name = "Articles"
  pageRef = "/posts"
  weight = 20

[[menus.main]]
  name = "About Us"
  pageRef = "/about"
  weight = 30

[[menus.main]]
  name = "Contact"
  pageRef = "/contact"
  weight = 40

# --- FOOTER MENU ---
[[menus.footer]]
  name = "About Us"
  pageRef = "/about"
  weight = 10

[[menus.footer]]
  name = "Contact Us"
  pageRef = "/contact"
  weight = 20

[[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 10

[[menu.footer]]
    name = "Terms and Conditions"
    url = "/terms-and-conditions/"
    weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true